// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AccountCreate.proto

package com.gt.scr.movie.grpc;

public final class AccountCreateGrpc {
  private AccountCreateGrpc() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_gt_scr_movie_grpc_AccountCreateGrpcRequestDTO_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_gt_scr_movie_grpc_AccountCreateGrpcRequestDTO_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_gt_scr_movie_grpc_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_gt_scr_movie_grpc_Empty_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023AccountCreate.proto\022\025com.gt.scr.movie." +
      "grpc\"t\n\033AccountCreateGrpcRequestDTO\022\020\n\010u" +
      "serName\030\001 \001(\t\022\020\n\010password\030\002 \001(\t\022\021\n\tfirst" +
      "Name\030\003 \001(\t\022\020\n\010lastName\030\004 \001(\t\022\014\n\004role\030\005 \001" +
      "(\t\"\007\n\005Empty2y\n\024CreateAccountService\022a\n\rc" +
      "reateAccount\0222.com.gt.scr.movie.grpc.Acc" +
      "ountCreateGrpcRequestDTO\032\034.com.gt.scr.mo" +
      "vie.grpc.EmptyB\025B\021AccountCreateGrpcP\001b\006p" +
      "roto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_gt_scr_movie_grpc_AccountCreateGrpcRequestDTO_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_gt_scr_movie_grpc_AccountCreateGrpcRequestDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_gt_scr_movie_grpc_AccountCreateGrpcRequestDTO_descriptor,
        new java.lang.String[] { "UserName", "Password", "FirstName", "LastName", "Role", });
    internal_static_com_gt_scr_movie_grpc_Empty_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_gt_scr_movie_grpc_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_gt_scr_movie_grpc_Empty_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
