// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AccountCreate.proto

package com.gt.scr.movie.grpc;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.gt.scr.movie.grpc.Empty)
    com.google.protobuf.MessageOrBuilder {
}
