// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Login.proto

package com.gt.scr.movie.grpc;

public final class LoginGrpc {
  private LoginGrpc() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_gt_scr_movie_grpc_LoginGrpcRequestDTO_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_gt_scr_movie_grpc_LoginGrpcRequestDTO_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_gt_scr_movie_grpc_LoginGrpcResponseDTO_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_gt_scr_movie_grpc_LoginGrpcResponseDTO_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Login.proto\022\025com.gt.scr.movie.grpc\"9\n\023" +
      "LoginGrpcRequestDTO\022\020\n\010userName\030\001 \001(\t\022\020\n" +
      "\010password\030\002 \001(\t\"1\n\024LoginGrpcResponseDTO\022" +
      "\r\n\005token\030\001 \001(\t\022\n\n\002id\030\002 \001(\t2p\n\014LoginServi" +
      "ce\022`\n\005login\022*.com.gt.scr.movie.grpc.Logi" +
      "nGrpcRequestDTO\032+.com.gt.scr.movie.grpc." +
      "LoginGrpcResponseDTOB\rB\tLoginGrpcP\001b\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_gt_scr_movie_grpc_LoginGrpcRequestDTO_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_gt_scr_movie_grpc_LoginGrpcRequestDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_gt_scr_movie_grpc_LoginGrpcRequestDTO_descriptor,
        new java.lang.String[] { "UserName", "Password", });
    internal_static_com_gt_scr_movie_grpc_LoginGrpcResponseDTO_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_gt_scr_movie_grpc_LoginGrpcResponseDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_gt_scr_movie_grpc_LoginGrpcResponseDTO_descriptor,
        new java.lang.String[] { "Token", "Id", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
