// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Login.proto

package com.gt.scr.movie.grpc;

public interface LoginGrpcResponseDTOOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.gt.scr.movie.grpc.LoginGrpcResponseDTO)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string token = 1;</code>
   * @return The token.
   */
  java.lang.String getToken();
  /**
   * <code>string token = 1;</code>
   * @return The bytes for token.
   */
  com.google.protobuf.ByteString
      getTokenBytes();

  /**
   * <code>string id = 2;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 2;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();
}
