// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Movie.proto

package com.gt.scr.movie.grpc;

public final class MovieGrpc {
  private MovieGrpc() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_gt_scr_movie_grpc_MovieGrpcCreateRequestDTO_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_gt_scr_movie_grpc_MovieGrpcCreateRequestDTO_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Movie.proto\022\025com.gt.scr.movie.grpc\032\014Co" +
      "mmon.proto\"O\n\031MovieGrpcCreateRequestDTO\022" +
      "\014\n\004name\030\001 \001(\t\022\024\n\014yearProduced\030\002 \001(\005\022\016\n\006r" +
      "ating\030\003 \001(\0012m\n\014MovieService\022]\n\013createMov" +
      "ie\0220.com.gt.scr.movie.grpc.MovieGrpcCrea" +
      "teRequestDTO\032\034.com.gt.scr.movie.grpc.Emp" +
      "tyB\rB\tMovieGrpcP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.gt.scr.movie.grpc.Common.getDescriptor(),
        });
    internal_static_com_gt_scr_movie_grpc_MovieGrpcCreateRequestDTO_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_gt_scr_movie_grpc_MovieGrpcCreateRequestDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_gt_scr_movie_grpc_MovieGrpcCreateRequestDTO_descriptor,
        new java.lang.String[] { "Name", "YearProduced", "Rating", });
    com.gt.scr.movie.grpc.Common.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
