// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Movie.proto

package com.gt.scr.movie.grpc;

/**
 * Protobuf type {@code com.gt.scr.movie.grpc.MovieGrpcCreateRequestDTO}
 */
public final class MovieGrpcCreateRequestDTO extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.gt.scr.movie.grpc.MovieGrpcCreateRequestDTO)
    MovieGrpcCreateRequestDTOOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MovieGrpcCreateRequestDTO.newBuilder() to construct.
  private MovieGrpcCreateRequestDTO(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MovieGrpcCreateRequestDTO() {
    name_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new MovieGrpcCreateRequestDTO();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private MovieGrpcCreateRequestDTO(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 16: {

            yearProduced_ = input.readInt32();
            break;
          }
          case 25: {

            rating_ = input.readDouble();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.gt.scr.movie.grpc.MovieGrpc.internal_static_com_gt_scr_movie_grpc_MovieGrpcCreateRequestDTO_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.gt.scr.movie.grpc.MovieGrpc.internal_static_com_gt_scr_movie_grpc_MovieGrpcCreateRequestDTO_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.gt.scr.movie.grpc.MovieGrpcCreateRequestDTO.class, com.gt.scr.movie.grpc.MovieGrpcCreateRequestDTO.Builder.class);
  }

  public static final int NAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object name_;
  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int YEARPRODUCED_FIELD_NUMBER = 2;
  private int yearProduced_;
  /**
   * <code>int32 yearProduced = 2;</code>
   * @return The yearProduced.
   */
  @java.lang.Override
  public int getYearProduced() {
    return yearProduced_;
  }

  public static final int RATING_FIELD_NUMBER = 3;
  private double rating_;
  /**
   * <code>double rating = 3;</code>
   * @return The rating.
   */
  @java.lang.Override
  public double getRating() {
    return rating_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
    }
    if (yearProduced_ != 0) {
      output.writeInt32(2, yearProduced_);
    }
    if (rating_ != 0D) {
      output.writeDouble(3, rating_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
    }
    if (yearProduced_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, yearProduced_);
    }
    if (rating_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(3, rating_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.gt.scr.movie.grpc.MovieGrpcCreateRequestDTO)) {
      return super.equals(obj);
    }
    com.gt.scr.movie.grpc.MovieGrpcCreateRequestDTO other = (com.gt.scr.movie.grpc.MovieGrpcCreateRequestDTO) obj;

    if (!getName()
        .equals(other.getName())) return false;
    if (getYearProduced()
        != other.getYearProduced()) return false;
    if (java.lang.Double.doubleToLongBits(getRating())
        != java.lang.Double.doubleToLongBits(
            other.getRating())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + YEARPRODUCED_FIELD_NUMBER;
    hash = (53 * hash) + getYearProduced();
    hash = (37 * hash) + RATING_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getRating()));
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.gt.scr.movie.grpc.MovieGrpcCreateRequestDTO parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.gt.scr.movie.grpc.MovieGrpcCreateRequestDTO parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.gt.scr.movie.grpc.MovieGrpcCreateRequestDTO parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.gt.scr.movie.grpc.MovieGrpcCreateRequestDTO parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.gt.scr.movie.grpc.MovieGrpcCreateRequestDTO parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.gt.scr.movie.grpc.MovieGrpcCreateRequestDTO parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.gt.scr.movie.grpc.MovieGrpcCreateRequestDTO parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.gt.scr.movie.grpc.MovieGrpcCreateRequestDTO parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.gt.scr.movie.grpc.MovieGrpcCreateRequestDTO parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.gt.scr.movie.grpc.MovieGrpcCreateRequestDTO parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.gt.scr.movie.grpc.MovieGrpcCreateRequestDTO parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.gt.scr.movie.grpc.MovieGrpcCreateRequestDTO parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.gt.scr.movie.grpc.MovieGrpcCreateRequestDTO prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.gt.scr.movie.grpc.MovieGrpcCreateRequestDTO}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.gt.scr.movie.grpc.MovieGrpcCreateRequestDTO)
      com.gt.scr.movie.grpc.MovieGrpcCreateRequestDTOOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gt.scr.movie.grpc.MovieGrpc.internal_static_com_gt_scr_movie_grpc_MovieGrpcCreateRequestDTO_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gt.scr.movie.grpc.MovieGrpc.internal_static_com_gt_scr_movie_grpc_MovieGrpcCreateRequestDTO_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gt.scr.movie.grpc.MovieGrpcCreateRequestDTO.class, com.gt.scr.movie.grpc.MovieGrpcCreateRequestDTO.Builder.class);
    }

    // Construct using com.gt.scr.movie.grpc.MovieGrpcCreateRequestDTO.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      name_ = "";

      yearProduced_ = 0;

      rating_ = 0D;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.gt.scr.movie.grpc.MovieGrpc.internal_static_com_gt_scr_movie_grpc_MovieGrpcCreateRequestDTO_descriptor;
    }

    @java.lang.Override
    public com.gt.scr.movie.grpc.MovieGrpcCreateRequestDTO getDefaultInstanceForType() {
      return com.gt.scr.movie.grpc.MovieGrpcCreateRequestDTO.getDefaultInstance();
    }

    @java.lang.Override
    public com.gt.scr.movie.grpc.MovieGrpcCreateRequestDTO build() {
      com.gt.scr.movie.grpc.MovieGrpcCreateRequestDTO result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.gt.scr.movie.grpc.MovieGrpcCreateRequestDTO buildPartial() {
      com.gt.scr.movie.grpc.MovieGrpcCreateRequestDTO result = new com.gt.scr.movie.grpc.MovieGrpcCreateRequestDTO(this);
      result.name_ = name_;
      result.yearProduced_ = yearProduced_;
      result.rating_ = rating_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.gt.scr.movie.grpc.MovieGrpcCreateRequestDTO) {
        return mergeFrom((com.gt.scr.movie.grpc.MovieGrpcCreateRequestDTO)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.gt.scr.movie.grpc.MovieGrpcCreateRequestDTO other) {
      if (other == com.gt.scr.movie.grpc.MovieGrpcCreateRequestDTO.getDefaultInstance()) return this;
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (other.getYearProduced() != 0) {
        setYearProduced(other.getYearProduced());
      }
      if (other.getRating() != 0D) {
        setRating(other.getRating());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.gt.scr.movie.grpc.MovieGrpcCreateRequestDTO parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.gt.scr.movie.grpc.MovieGrpcCreateRequestDTO) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private int yearProduced_ ;
    /**
     * <code>int32 yearProduced = 2;</code>
     * @return The yearProduced.
     */
    @java.lang.Override
    public int getYearProduced() {
      return yearProduced_;
    }
    /**
     * <code>int32 yearProduced = 2;</code>
     * @param value The yearProduced to set.
     * @return This builder for chaining.
     */
    public Builder setYearProduced(int value) {
      
      yearProduced_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 yearProduced = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearYearProduced() {
      
      yearProduced_ = 0;
      onChanged();
      return this;
    }

    private double rating_ ;
    /**
     * <code>double rating = 3;</code>
     * @return The rating.
     */
    @java.lang.Override
    public double getRating() {
      return rating_;
    }
    /**
     * <code>double rating = 3;</code>
     * @param value The rating to set.
     * @return This builder for chaining.
     */
    public Builder setRating(double value) {
      
      rating_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double rating = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearRating() {
      
      rating_ = 0D;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.gt.scr.movie.grpc.MovieGrpcCreateRequestDTO)
  }

  // @@protoc_insertion_point(class_scope:com.gt.scr.movie.grpc.MovieGrpcCreateRequestDTO)
  private static final com.gt.scr.movie.grpc.MovieGrpcCreateRequestDTO DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.gt.scr.movie.grpc.MovieGrpcCreateRequestDTO();
  }

  public static com.gt.scr.movie.grpc.MovieGrpcCreateRequestDTO getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MovieGrpcCreateRequestDTO>
      PARSER = new com.google.protobuf.AbstractParser<MovieGrpcCreateRequestDTO>() {
    @java.lang.Override
    public MovieGrpcCreateRequestDTO parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new MovieGrpcCreateRequestDTO(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MovieGrpcCreateRequestDTO> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MovieGrpcCreateRequestDTO> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.gt.scr.movie.grpc.MovieGrpcCreateRequestDTO getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

