version: "3.7"
services:
  timezone-app:
    container_name: local.timezone-app
    depends_on:
      - db
    build:
      context: application
    ports:
      - "8080:8080"
    environment:
      - "DATABASE_HOST=local.database"
      - "DATABASE_PORT=6379"
      - "SPRING_PROFILES_ACTIVE=prod"
    networks:
      - overlay

  db:
    image: redis
    container_name: local.database
    ports:
      - "6379:6379"
    networks:
      - overlay

networks:
  overlay: