version: "3.7"
services:
#  timezone-app:
#    container_name: local.timezone-app
#    build:
#      context: application
#    ports:
#      - "8080:8080"
#    networks:
#      - overlay

  db:
    image: redis
    container_name: local.redis
    ports:
      - "6379:6379"
    networks:
      - overlay

networks:
  overlay: