version: "3.7"
services:
  movie-app:
    container_name: local.movie-app
    depends_on:
      - mysql
    build:
      context: application
    ports:
      - "9090:9090"
      - "9091:9091"
      - "9900:9900"
      - "8443:8443"
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"
      - "SERVER_PORT=9090"
      - "SERVER_MGT_PORT=9091"
      - "MYSQL_HOST=local.mysql"
      - "MYSQL_PWD=password"
      - "MYSQL_USER=root"
      - "MYSQL_DB_NAME=movieMetadata"
      - "USER_HOST=local.user-app"
      - "USER_PORT=7070"
    networks:
      - overlay

  user-app:
    container_name: local.user-app
    depends_on:
      - mysql
    build:
      context: user
    ports:
      - "7070:7070"
      - "7071:7071"
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"
      - "SERVER_PORT=7070"
      - "SERVER_MGT_PORT=7071"
      - "MYSQL_HOST=local.mysql"
      - "MYSQL_PWD=password"
      - "MYSQL_USER=root"
      - "MYSQL_DB_NAME=movieMetadata"
    networks:
      - overlay

  api-gateway:
    container_name: local.api-gateway
    depends_on:
      - movie-app
    build:
      context: api-gateway
    ports:
      - "8080:8080"
    networks:
      - overlay

#  ui-app:
#    container_name: local.ui-app
#    depends_on:
#      - movie-app
#    build:
#      context: ui
#    ports:
#      - "8080:8080"
#    environment:
#      - "OAUTH_CLIENT_ID_GITHUB=${OAUTH_CLIENT_ID_GITHUB}"
#      - "OAUTH_CLIENT_SECRET_GITHUB=${OAUTH_CLIENT_SECRET_GITHUB}"
#      - "OAUTH_CLIENT_ID_GOOGLE=${OAUTH_CLIENT_ID_GOOGLE}"
#      - "OAUTH_CLIENT_SECRET_GOOGLE=${OAUTH_CLIENT_SECRET_GOOGLE}"
#    networks:
#      - overlay

  mysql:
    image: mysql:8.0.19
    container_name: local.mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=password"
      - "MYSQL_DATABASE=movieMetadata"
    networks:
      - overlay

networks:
  overlay: