spring:
  active: local
  liquibase:
    changeLog: classpath:db.changelog/dbchangelog.sql

server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /api

management:
  server.port: ${SERVER_MGT_PORT:8081}
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure.include: health, mappings, metrics
      path-mapping:
        health: healthcheck

auth:
  tokenDuration: ${TOKEN_DURATION:1h}
  secret: ${SECRET:19CA249C582715657BDCAB1FB31E69F854443A4FE3CBAFFD215E3F3676}

database:
  host: ${DATABASE_HOST:localhost}
  port: ${DATABASE_PORT:6379}
  duplicateInterval: ${DUPLICATE_INTERVAL:10ms}
  connectionTimeout: ${CONNECTION_TIMEOUT:10s}
  commandTimeout: ${COMMAND_TIMEOUT:500ms}

mysql:
  driver: "com.mysql.cj.jdbc.Driver"
  host: ${MYSQL_HOST:localhost}
  port: ${MYSQL_PORT:3306}
  user: ${MYSQL_USER:user}
  password: ${MYSQL_PWD:password}
  minPoolSize: 2
  maxPoolSize: 2
  database: ${MYSQL_DB_NAME:movieMetadata}