spring:
  active: local

server:
  servlet:
    context-path: /api

timezoneApp:
  maxUserNameLength: 15 #Add Test
  minUserNameLength: 8 #Add Test
  maxPasswordLength: 15 #Add Test
  minPasswordLength: 8 #Add Test

database:
  host: ${REDIS_HOST:localhost}
  port: ${REDIS_PORT:6379}