spring:
  active: local

server:
  servlet:
    context-path: /api

auth:
  tokenDuration: ${TOKEN_DURATION:6h}
  secret: ${SECRET:19CA249C582715657BDCAB1FB31E69F854443A4FE3CBAFFD215E3F3676}

database:
  host: ${REDIS_HOST:localhost}
  port: ${REDIS_PORT:6379}