spring:
  active: prod
  liquibase:
    changeLog: classpath:db.changelog/dbchangelog.sql
  webflux:
    base-path: /api/content

server:
  port: ${SERVER_PORT:9090}

management:
  server.port: ${SERVER_MGT_PORT:9091}
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure.include: health, mappings, metrics
      path-mapping:
        health: healthcheck

user:
  host: ${USER_HOST:localhost}
  port: ${USER_PORT:7070}

auth:
  tokenDuration: ${TOKEN_DURATION:3650D}
  secret: ${SECRET:19CA249C582715657BDCAB1FB31E69F854443A4FE3CBAFFD215E3F3676}

mysql:
  driver: "com.mysql.cj.jdbc.Driver"
  host: ${MYSQL_HOST:localhost}
  port: ${MYSQL_PORT:3306}
  user: ${MYSQL_USER:user}
  password: ${MYSQL_PWD:password}
  minPoolSize: 2
  maxPoolSize: 2
  database: ${MYSQL_DB_NAME:movieMetadata}
  schema: MOVIE_SCHEMA