// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserService.proto

package com.gt.scr.movie.grpc;

public final class AccountCreateGrpc {
  private AccountCreateGrpc() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_gt_scr_movie_grpc_AccountCreateGrpcRequestDTO_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_gt_scr_movie_grpc_AccountCreateGrpcRequestDTO_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_gt_scr_movie_grpc_FetchUserDetailsByIdGrpcRequestDTO_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_gt_scr_movie_grpc_FetchUserDetailsByIdGrpcRequestDTO_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_gt_scr_movie_grpc_FetchUserDetailsByNameGrpcRequestDTO_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_gt_scr_movie_grpc_FetchUserDetailsByNameGrpcRequestDTO_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_gt_scr_movie_grpc_UserDetailsGrpcResponseDTO_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_gt_scr_movie_grpc_UserDetailsGrpcResponseDTO_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021UserService.proto\022\025com.gt.scr.movie.gr" +
      "pc\032\033google/protobuf/empty.proto\"\256\001\n\033Acco" +
      "untCreateGrpcRequestDTO\022\020\n\010userName\030\001 \001(" +
      "\t\022\020\n\010password\030\002 \001(\t\022\021\n\tfirstName\030\003 \001(\t\022\020" +
      "\n\010lastName\030\004 \001(\t\022\014\n\004role\030\005 \001(\t\022\023\n\013dateOf" +
      "Birth\030\006 \001(\t\022\016\n\006gender\030\007 \001(\t\022\023\n\013homeCount" +
      "ry\030\010 \001(\t\"0\n\"FetchUserDetailsByIdGrpcRequ" +
      "estDTO\022\n\n\002id\030\001 \001(\t\"4\n$FetchUserDetailsBy" +
      "NameGrpcRequestDTO\022\014\n\004name\030\001 \001(\t\"\330\001\n\032Use" +
      "rDetailsGrpcResponseDTO\022\020\n\010userName\030\001 \001(" +
      "\t\022\020\n\010password\030\002 \001(\t\022\021\n\tfirstName\030\003 \001(\t\022\020" +
      "\n\010lastName\030\004 \001(\t\022\014\n\004role\030\005 \001(\t\022\n\n\002id\030\006 \001" +
      "(\t\022\023\n\013dateOfBirth\030\007 \001(\t\022-\n\006gender\030\010 \001(\0162" +
      "\035.com.gt.scr.movie.grpc.Gender\022\023\n\013homeCo" +
      "untry\030\t \001(\t*V\n\006Gender\022\026\n\022GENDER_UNSPECIF" +
      "IED\020\000\022\017\n\013GENDER_MALE\020\001\022\021\n\rGENDER_FEMALE\020" +
      "\002\022\020\n\014GENDER_OTHER\020\0032\227\002\n\020FetchUserService" +
      "\022~\n\016fetchUsersById\0229.com.gt.scr.movie.gr" +
      "pc.FetchUserDetailsByIdGrpcRequestDTO\0321." +
      "com.gt.scr.movie.grpc.UserDetailsGrpcRes" +
      "ponseDTO\022\202\001\n\020fetchUsersByName\022;.com.gt.s" +
      "cr.movie.grpc.FetchUserDetailsByNameGrpc" +
      "RequestDTO\0321.com.gt.scr.movie.grpc.UserD" +
      "etailsGrpcResponseDTO2s\n\024CreateAccountSe" +
      "rvice\022[\n\rcreateAccount\0222.com.gt.scr.movi" +
      "e.grpc.AccountCreateGrpcRequestDTO\032\026.goo" +
      "gle.protobuf.EmptyB\025B\021AccountCreateGrpcP" +
      "\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
        });
    internal_static_com_gt_scr_movie_grpc_AccountCreateGrpcRequestDTO_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_gt_scr_movie_grpc_AccountCreateGrpcRequestDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_gt_scr_movie_grpc_AccountCreateGrpcRequestDTO_descriptor,
        new java.lang.String[] { "UserName", "Password", "FirstName", "LastName", "Role", "DateOfBirth", "Gender", "HomeCountry", });
    internal_static_com_gt_scr_movie_grpc_FetchUserDetailsByIdGrpcRequestDTO_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_gt_scr_movie_grpc_FetchUserDetailsByIdGrpcRequestDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_gt_scr_movie_grpc_FetchUserDetailsByIdGrpcRequestDTO_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_com_gt_scr_movie_grpc_FetchUserDetailsByNameGrpcRequestDTO_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_gt_scr_movie_grpc_FetchUserDetailsByNameGrpcRequestDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_gt_scr_movie_grpc_FetchUserDetailsByNameGrpcRequestDTO_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_com_gt_scr_movie_grpc_UserDetailsGrpcResponseDTO_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_gt_scr_movie_grpc_UserDetailsGrpcResponseDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_gt_scr_movie_grpc_UserDetailsGrpcResponseDTO_descriptor,
        new java.lang.String[] { "UserName", "Password", "FirstName", "LastName", "Role", "Id", "DateOfBirth", "Gender", "HomeCountry", });
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
