// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserService.proto

package com.gt.scr.movie.grpc;

public interface FetchUserDetailsByIdGrpcRequestDTOOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.gt.scr.movie.grpc.FetchUserDetailsByIdGrpcRequestDTO)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();
}
