// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserService.proto

package com.gt.scr.movie.grpc;

public interface UserDetailsGrpcResponseDTOOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.gt.scr.movie.grpc.UserDetailsGrpcResponseDTO)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string userName = 1;</code>
   * @return The userName.
   */
  java.lang.String getUserName();
  /**
   * <code>string userName = 1;</code>
   * @return The bytes for userName.
   */
  com.google.protobuf.ByteString
      getUserNameBytes();

  /**
   * <code>string password = 2;</code>
   * @return The password.
   */
  java.lang.String getPassword();
  /**
   * <code>string password = 2;</code>
   * @return The bytes for password.
   */
  com.google.protobuf.ByteString
      getPasswordBytes();

  /**
   * <code>string firstName = 3;</code>
   * @return The firstName.
   */
  java.lang.String getFirstName();
  /**
   * <code>string firstName = 3;</code>
   * @return The bytes for firstName.
   */
  com.google.protobuf.ByteString
      getFirstNameBytes();

  /**
   * <code>string lastName = 4;</code>
   * @return The lastName.
   */
  java.lang.String getLastName();
  /**
   * <code>string lastName = 4;</code>
   * @return The bytes for lastName.
   */
  com.google.protobuf.ByteString
      getLastNameBytes();

  /**
   * <code>string role = 5;</code>
   * @return The role.
   */
  java.lang.String getRole();
  /**
   * <code>string role = 5;</code>
   * @return The bytes for role.
   */
  com.google.protobuf.ByteString
      getRoleBytes();

  /**
   * <code>string id = 6;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 6;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string dateOfBirth = 7;</code>
   * @return The dateOfBirth.
   */
  java.lang.String getDateOfBirth();
  /**
   * <code>string dateOfBirth = 7;</code>
   * @return The bytes for dateOfBirth.
   */
  com.google.protobuf.ByteString
      getDateOfBirthBytes();

  /**
   * <code>.com.gt.scr.movie.grpc.Gender gender = 8;</code>
   * @return The enum numeric value on the wire for gender.
   */
  int getGenderValue();
  /**
   * <code>.com.gt.scr.movie.grpc.Gender gender = 8;</code>
   * @return The gender.
   */
  com.gt.scr.movie.grpc.Gender getGender();

  /**
   * <code>string homeCountry = 9;</code>
   * @return The homeCountry.
   */
  java.lang.String getHomeCountry();
  /**
   * <code>string homeCountry = 9;</code>
   * @return The bytes for homeCountry.
   */
  com.google.protobuf.ByteString
      getHomeCountryBytes();
}
