--liquibase formatted sql

--changeset movie:1
create SCHEMA IF NOT EXISTS MOVIE_SCHEMA;

create TABLE IF NOT EXISTS USER (
    ID VARCHAR(40) NOT NULL,
    USER_NAME VARCHAR(40) UNIQUE NOT NULL,
    FIRST_NAME VARCHAR(256) NOT NULL,
    LAST_NAME VARCHAR(256) NOT NULL,
    PASSWORD VARCHAR(256) NOT NULL,
    ROLES VARCHAR(256) NOT NULL,
    PRIMARY KEY (id)
) ENGINE=INNODB;

create TABLE IF NOT EXISTS MOVIE (
    ID VARCHAR(40) NOT NULL,
    USER_ID VARCHAR(40) NOT NULL,
    NAME VARCHAR(256) NOT NULL,
    YEAR_PRODUCED SMALLINT NOT NULL,
    RATING DECIMAL(4,2) NOT NULL,
    CREATION_TIMESTAMP BIGINT NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (USER_ID) REFERENCES USER(id) ON delete CASCADE
) ENGINE=INNODB;
