--liquibase formatted sql

--changeset movie:1
CREATE SCHEMA IF NOT EXISTS MOVIE_SCHEMA;

CREATE TABLE IF NOT EXISTS MOVIE (
    ID VARCHAR(40) NOT NULL,
    NAME VARCHAR(256) NOT NULL,
    YEAR_PRODUCED VARCHAR(3500) NOT NULL,
    RATING VARCHAR(200) NOT NULL,
    CREATION_TIMESTAMP BIGINT NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS USER (
    ID VARCHAR(40) NOT NULL,
    USER_NAME VARCHAR(40) UNIQUE NOT NULL,
    FIRST_NAME VARCHAR(256) NOT NULL,
    LAST_NAME VARCHAR(256) NOT NULL,
    PASSWORD VARCHAR(256) NOT NULL,
    ROLES VARCHAR(256) NOT NULL,
    PRIMARY KEY (id)
);

