--liquibase formatted sql

--changeset movie:1
create SCHEMA IF NOT EXISTS MOVIE_SCHEMA;

create TABLE IF NOT EXISTS USER (
    ID VARCHAR(40) NOT NULL,
    USER_NAME VARCHAR(40) UNIQUE NOT NULL,
    FIRST_NAME VARCHAR(256) NOT NULL,
    LAST_NAME VARCHAR(256) NOT NULL,
    PASSWORD VARCHAR(256) NOT NULL,
    ROLES VARCHAR(256) NOT NULL,
    PRIMARY KEY (id)
) ENGINE=INNODB;

create TABLE IF NOT EXISTS MOVIE (
    ID VARCHAR(40) NOT NULL,
    USER_ID VARCHAR(40) NOT NULL,
    NAME VARCHAR(256) NOT NULL,
    YEAR_PRODUCED SMALLINT NOT NULL,
    RATING DECIMAL(4,2) NOT NULL,
    CREATION_TIMESTAMP BIGINT NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (USER_ID) REFERENCES USER(id) ON delete CASCADE
) ENGINE=INNODB;

--changeset movie:2
DELETE FROM MOVIE;
DELETE FROM USER;

--changeset movie:3
insert INTO USER (ID, USER_NAME, FIRST_NAME, LAST_NAME, PASSWORD, ROLES) values ('dcba7802-2eae-42b2-818e-a27f8f380088', 'admin', 'Gaurav',
'Tyagi', '{bcrypt}$2a$10$ZiuCPqHY0hU1N4fgAKaV6uwLCN96lU0aD.llqQmX5L8TfQkjTz2XS', 'ADMIN');

--changeset movie:4
create TABLE IF NOT EXISTS EVENTS (
    ID VARCHAR(40) NOT NULL,
    USER_ID VARCHAR(40) NOT NULL,
    TYPE VARCHAR(256) NOT NULL,
    PAYLOAD BLOB,
    CREATION_TIMESTAMP BIGINT NOT NULL,
    PRIMARY KEY (id)
) ENGINE=INNODB;