--liquibase formatted sql

--changeset user:1
create SCHEMA IF NOT EXISTS USER_SCHEMA;
USE USER_SCHEMA;

create TABLE IF NOT EXISTS USER (
    ID VARCHAR(40) NOT NULL,
    USER_NAME VARCHAR(40) UNIQUE NOT NULL,
    FIRST_NAME VARCHAR(256) NOT NULL,
    LAST_NAME VARCHAR(256) NOT NULL,
    PASSWORD VARCHAR(256) NOT NULL,
    ROLES VARCHAR(256) NOT NULL,
    PRIMARY KEY (id)
) ENGINE=INNODB;

--changeset user:2
DELETE FROM USER;

--changeset user:3
insert INTO USER (ID, USER_NAME, FIRST_NAME, LAST_NAME, PASSWORD, ROLES) values ('dcba7802-2eae-42b2-818e-a27f8f380088', 'admin', 'Gaurav',
'Tyagi', '{bcrypt}$2a$10$ZiuCPqHY0hU1N4fgAKaV6uwLCN96lU0aD.llqQmX5L8TfQkjTz2XS', 'ADMIN');

--changeset user:4
create TABLE IF NOT EXISTS EVENTS (
    ID VARCHAR(40) NOT NULL,
    OWNER_USER VARCHAR(40) NOT NULL,
    ORIGINATOR_USER VARCHAR(40) NOT NULL,
    TYPE VARCHAR(256) NOT NULL,
    PAYLOAD BLOB NOT NULL,
    CREATION_TIMESTAMP BIGINT NOT NULL,
    PRIMARY KEY (id)
) ENGINE=INNODB;