name: Functional Test

on:
  push:
    branches:
      - master
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew clean build --info

    - name: Build the docker-compose stack
      env:
        OAUTH_CLIENT_ID_GITHUB: ${{ secrets.OAUTH_CLIENT_ID_GITHUB }}
        OAUTH_CLIENT_SECRET_GITHUB: ${{ secrets.OAUTH_CLIENT_SECRET_GITHUB }}
        OAUTH_CLIENT_ID_GOOGLE: ${{ secrets.OAUTH_CLIENT_ID_GOOGLE }}
        OAUTH_CLIENT_SECRET_GOOGLE: ${{ secrets.OAUTH_CLIENT_SECRET_GOOGLE }}
      run: docker-compose up -d

    - name: Sleep
      uses: jakejarvis/wait-action@master
      with:
        time: '30s'

    - name: Check running containers
      run: docker ps

    - name: Run test suite
      run: ./gradlew remoteFunctional --info

#   Enable below only for DEBUG

#    - name: Show container logs
#      if: always()
#      run: docker logs local.movie-app
